name: dancee_app
description: Example project for Vader Framework.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  # Flutter dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Vader dependencies:
  vader_app: ^0.3.2
  vader_core: ^0.4.2

  # Design dependencies:
  cupertino_icons: ^1.0.8
  dancee_shared:
    path: ../dancee_shared
  dancee_design:
    path: ../dancee_design

  # Package dependencies:
  dio: ^5.8.0+1
  uuid: ^4.5.1
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  slang_build_runner: ^4.5.0
  json_serializable: ^6.9.0
  go_router_builder: ^2.3.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  bloc_test: ^10.0.0
  freezed: ^2.5.7
  test: ^1.25.15


flutter:
  uses-material-design: true
  assets:
    - ../dancee_design/assets/icons/