name: dancee_app
description: Example project for Vader Framework.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  # Flutter dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Vader dependencies:
  vader_app: ^0.3.2
  vader_core: ^0.4.1

  # Design dependencies:
  cupertino_icons: ^1.0.8
  dancee_design:
    path: ../dancee_design

  # Package dependencies:
  uuid: ^4.5.1
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  surrealdb: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  slang_build_runner: ^4.5.0
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  bloc_test: ^10.0.0
  freezed: ^2.5.7
  test: ^1.25.15


flutter:
  uses-material-design: true