name: dancee_app
description: Example project for Vader Framework.
#resolution: workspace
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dancee_design:
    path: ../dancee_design

  vader_app: ^0.3.2
  vader_core: ^0.4.1

  uuid: ^4.5.1
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  surrealdb: ^1.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  #mek_data_class_generator: 1.5.1
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  slang_build_runner: ^4.5.0
  bloc_test: ^10.0.0
  freezed: ^2.5.7
  test: ^1.25.15

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true