version: '3'
# Manual is here: https://taskfile.dev/usage/

tasks:
  help:
    aliases: [default]
    cmd: "task --list"

  update-dependencies:
    desc: "Updates Dart dependencies"
    cmd: "fvm dart pub get"

  generate-goldens:
    cmd: "fvm flutter test --update-goldens"
    desc: "Update Golden tests"

  watch-build-runner:
    aliases: [build-runner-watch]
    cmd: "fvm dart run build_runner watch --delete-conflicting-outputs"
    desc: "Runs code generation with watch (build_runner)"

  run-build-runner:
    cmd: "fvm dart run build_runner build --delete-conflicting-outputs"
    desc: "Runs code generation (build_runner)"

  run-app:
    cmd: "fvm flutter run -t lib/main.dart"
    desc: "Run application"

  run-test:
    cmd: "fvm flutter test"
    desc: "Run tests"

  run-slang:
    cmd: "fvm dart run slang"
    desc: "Generate translation files"

  watch-slang:
    cmd: "fvm dart run slang watch"
    desc: "Generate translation files"

  deploy:
    cmd: "flyctl deploy"
    desc: "Deploy service to Fly.io"
    deps:
      - build

  launch:
    cmd: "flyctl launch"
    desc: "Initialize service to Fly.io"

  build:
    cmd: "flutter build web --release"
    desc: "Build web app"