version: '3'

tasks:
  help:
    aliases: [default]
    cmd: "task --list"

  update-dependencies:
    desc: "Updates Dart dependencies"
    cmd: "fvm dart pub get"

  watch-build-runner:
    aliases: [build-runner-watch]
    cmd: "fvm dart run build_runner watch --delete-conflicting-outputs"
    desc: "Runs code generation with watch (build_runner)"

  run-build-runner:
    cmd: "fvm dart run build_runner build --delete-conflicting-outputs"
    desc: "Runs code generation (build_runner)"

  update-translations:
    cmd: "fvm dart run slang"
    desc: "Update translations"

  update-goldens:
    cmd: "fvm flutter test --update-goldens"
    desc: "Update Golden tests"

  run-app:
    cmd: "fvm flutter run -t lib/main.dart"
    desc: "Run application"

  run-test:
    cmd: "fvm flutter test"
    desc: "Run tests"
