name: serinus_service
description: "A new Serinus application"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  serinus: ^1.0.3
  vader_core: ^0.4.2
  google_geocoding_api: ^1.5.2
  dancee_shared:
    path: ../../dancee_shared

dev_dependencies:
  freezed: ^2.5.7
  hotreloader: ^4.1.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
