version: '3'
# Manual is here: https://taskfile.dev/usage/

interval: 1000ms

tasks:
  help:
    aliases: [default]
    cmd: "task --list"

  update-dependencies:
    desc: "Updates Dart dependencies"
    cmd: "fvm dart pub get"

  watch-build-runner:
    aliases: [build-runner-watch]
    cmd: "fvm dart run build_runner watch --delete-conflicting-outputs"
    desc: "Runs code generation with watch (build_runner)"

  build-design:
    cmd: "./bin/design_builder -s src -o lib -p dancee_design"
    desc: "Generate Dart design files in lib folder"
    sources:
      - 'src/**/*.dart'

  run-build-runner:
    cmd: "fvm dart run build_runner build --delete-conflicting-outputs"
    desc: "Runs code generation (build_runner)"

  update-goldens:
    cmd: "fvm flutter test --update-goldens"
    desc: "Update Golden tests"

  run-storybook:
    cmd: "fvm flutter run -t storybook/storybook.dart"
    desc: "Run storybook"

  run-test:
    cmd: "fvm flutter test"
    desc: "Run tests"

  create-component:
    cmd: "./bin/code_builder -t component -p dancee_design -d src/design/"
    desc: "Create new component"
