name: dancee_shared
description: Shared package in Dancee project
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  uuid: ^4.5.1
  date_time: ^0.11.0
  vader_core: ^0.4.2
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  lints: ^5.0.0
  test: ^1.25.15
